include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    unnecessary_this: true
    sort_constructors_first: true
    sized_box_for_whitespace: true
    prefer_single_quotes: true
