name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  cached_network_image: ^3.2.2
  image_picker: ^0.8.5+3
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  envied: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  freezed: ^2.1.1
  envied_generator: ^0.2.3

dependency_overrides:
  analyzer: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
